In [ ]:
pip install cassandra-driver
pip install python-dotenv

Collecting cassandra-driver
  Downloading cassandra_driver-3.29.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting geomet>=1.1 (from cassandra-driver)
  Downloading geomet-1.1.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from geomet>=1.1->cassandra-driver) (8.3.1)
Downloading cassandra_driver-3.29.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (374 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.4/374.4 kB 7.6 MB/s eta 0:00:00
Downloading geomet-1.1.0-py3-none-any.whl (31 kB)
Installing collected packages: geomet, cassandra-driver
Successfully installed cassandra-driver-3.29.3 geomet-1.1.0

In [2]:
!python -c "import cassandra; print(cassandra.__version__)"

3.29.3

In [ ]:
from dotenv import load_dotenv
load_dotenv()
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
cloud_config= {
 'secure_connect_bundle':'/content/secure-connect-casandaraks.zip'
 }
auth_provider = PlainTextAuthProvider(
    os.getenv("CASSANDRA_USER"),
    os.getenv("CASSANDRA_PASS")
)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for bc1016a8-ac07-42a9-a239-a40c36b9a0eb-us-east1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for bc1016a8-ac07-42a9-a239-a40c36b9a0eb-us-east1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for bc1016a8-ac07-42a9-a239-a40c36b9a0eb-us-east1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version

In [5]:
session.set_keyspace('ks1')
row = cluster.metadata.keyspaces['ks1']
from pprint import pprint
pprint(vars(row))

{'aggregates': {},
 'durable_writes': True,
 'functions': {},
 'graph_engine': None,
 'indexes': {},
 'name': 'ks1',
 'replication_strategy': <cassandra.metadata.NetworkTopologyStrategy object at 0x78404dca0a10>,
 'tables': {'kickstarter': <cassandra.metadata.TableMetadataV3 object at 0x78404dca3650>},
 'user_types': {},
 'views': {}}

In [6]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/kick_starter.csv')

# Print the first 10 rows of the DataFrame in a table format
print("First 10 rows of the DataFrame:")
display(df.head(10))

# Print the shape of the DataFrame
print("\nShape of the DataFrame:")
print(df.shape)

First 10 rows of the DataFrame:

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00

Shape of the DataFrame:
(378661, 15)

## Dropped usd_pledged coloumn

In [7]:
df = df.drop(columns=['usd pledged'])

print("DataFrame after dropping 'usd_pledged' column:")
display(df.head())

DataFrame after dropping 'usd_pledged' column:

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## unifing column names

In [8]:
df = df.rename(columns={'ID': 'id'})

print("DataFrame after renaming 'ID' to 'id':")
display(df.head())

DataFrame after renaming 'ID' to 'id':

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## Checking for duplicates

In [9]:
print(f"DataFrame shape before dropping duplicates: {df.shape}")

duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_rows}")

df = df.drop_duplicates()

print(f"DataFrame shape after dropping duplicates: {df.shape}")
display(df.head())

DataFrame shape before dropping duplicates: (378661, 14)
Number of duplicate rows found: 0
DataFrame shape after dropping duplicates: (378661, 14)

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## Handling missing values

In [12]:
print("Missing values per column:")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

Missing values per column:
name    4
dtype: int64

In [11]:
print("DataFrame Info (including data types):")
df.info()

DataFrame Info (including data types):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                378661 non-null  int64
 1   name              378657 non-null  object
 2   category          378661 non-null  object
 3   main_category     378661 non-null  object
 4   currency          378661 non-null  object
 5   deadline          378661 non-null  object
 6   goal              378661 non-null  float64
 7   launched          378661 non-null  object
 8   pledged           378661 non-null  float64
 9   state             378661 non-null  object
 10  backers           378661 non-null  int64
 11  country           378661 non-null  object
 12  usd_pledged_real  378661 non-null  float64
 13  usd_goal_real     378661 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 40.4+ MB

In [13]:
print(f"DataFrame shape before dropping missing values in 'name': {df.shape}")

df = df.dropna(subset=['name'])

print(f"DataFrame shape after dropping missing values in 'name': {df.shape}")

DataFrame shape before dropping missing values in 'name': (378661, 14)
DataFrame shape after dropping missing values in 'name': (378657, 14)

## Drop projects where state = live

In [14]:
print(f"DataFrame shape before dropping 'live' projects: {df.shape}")

df = df[df['state'] != 'live']

print(f"DataFrame shape after dropping 'live' projects: {df.shape}")

DataFrame shape before dropping 'live' projects: (378657, 14)
DataFrame shape after dropping 'live' projects: (375858, 14)

## CampaignDuration (in days)

In [15]:
df['launched'] = pd.to_datetime(df['launched'])
df['deadline'] = pd.to_datetime(df['deadline'])

df['CampaignDuration'] = (df['deadline'] - df['launched']).dt.days

print("DataFrame with 'CampaignDuration' column:")
display(df.head())
print("\nData type of 'CampaignDuration' column:")
print(df['CampaignDuration'].dtype)

DataFrame with 'CampaignDuration' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55

Data type of 'CampaignDuration' column:
int64

## FundingRatio
FundingRatio =
usd_pledged_real/
usd_goal_real

In [16]:
df['FundingRatio'] = df['usd_pledged_real'] / df['usd_goal_real']

print("DataFrame with 'FundingRatio' column:")
display(df.head())

DataFrame with 'FundingRatio' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795

## GoalCategory
– Low Goal (< $10,000)
– Medium Goal ($10,000 – $100,000)
– High Goal (> $100,000)

In [17]:
bins = [-float('inf'), 10000, 100000, float('inf')]
labels = ['Low Goal', 'Medium Goal', 'High Goal']

df['GoalCategory'] = pd.cut(df['usd_goal_real'], bins=bins, labels=labels, right=False)

print("DataFrame with 'GoalCategory' column:")
display(df.head())
print("\nValue counts for 'GoalCategory':")
print(df['GoalCategory'].value_counts())

DataFrame with 'GoalCategory' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000,Low Goal
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700,Medium Goal
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889,Medium Goal
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200,Low Goal
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795,Medium Goal

Value counts for 'GoalCategory':
GoalCategory
Low Goal       231823
Medium Goal    128011
High Goal       16024
Name: count, dtype: int64

##  LaunchMonth

In [18]:
df['LaunchMonth'] = df['launched'].dt.month

print("DataFrame with 'LaunchMonth' column:")
display(df.head())

DataFrame with 'LaunchMonth' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory,LaunchMonth
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000,Low Goal,8
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700,Medium Goal,9
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889,Medium Goal,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200,Low Goal,3
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795,Medium Goal,7

## Create the Table

In [19]:
session.execute("""
DROP TABLE IF EXISTS ks1.kickstarter;
""")
session.execute("""
CREATE TABLE IF NOT EXISTS ks1.kickstarter (
    id int PRIMARY KEY,
    name text,
    category text,
    main_category text,
    currency text,
    deadline date,
    goal double,
    launched timestamp,
    pledged double,
    state text,
    backers int,
    country text,
    usd_pledged_real double,
    usd_goal_real double,
    campaignduration int,
    fundingratio double,
    goalcategory text,
    launchmonth int
)
""")

### The deadline and launched columns were converted to datetime using pandas to match the date and timestamp data types defined in the Cassandra table schema

In [20]:
df['deadline'] = pd.to_datetime(df['deadline'])
df['launched'] = pd.to_datetime(df['launched'])

## Insert first 5000 rows into table

In [21]:
import datetime

df = df.reset_index(drop=True)  # Reset the index after dropping rows
i, j = df.shape

# Loop through each row and insert into Cassandra, limiting to first 5000 rows
for x in range(0, min(5000, i)):
    session.execute("""
    INSERT INTO ks1.kickstarter (
        id, name, category, main_category, currency,
        deadline, goal, launched, pledged, state,
        backers, country, usd_pledged_real, usd_goal_real,
        campaignduration, fundingratio, goalcategory, launchmonth
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        int(df.loc[x, 'id']),
        df.loc[x, 'name'],
        df.loc[x, 'category'],
        df.loc[x, 'main_category'],
        df.loc[x, 'currency'],
        df.loc[x, 'deadline'].date(),          # Convert to native Python date object
        float(df.loc[x, 'goal']),
        df.loc[x, 'launched'].to_pydatetime(), # Convert to native Python datetime object
        float(df.loc[x, 'pledged']),
        df.loc[x, 'state'],
        int(df.loc[x, 'backers']),
        df.loc[x, 'country'],
        float(df.loc[x, 'usd_pledged_real']),
        float(df.loc[x, 'usd_goal_real']),
        int(df.loc[x, 'CampaignDuration']),
        float(df.loc[x, 'FundingRatio']),
        df.loc[x, 'GoalCategory'],
        int(df.loc[x, 'LaunchMonth'])
    ))
    print(df.loc[x, 'name'], "has been inserted")

# Check inserted rows
rows = session.execute("SELECT * FROM ks1.kickstarter;")
for row in rows:
    print(row)

Streaming output truncated to the last 5000 lines.
Row(id=1001524172, backers=20, campaignduration=44, category='Photography', country='US', currency='USD', deadline=Date(15179), fundingratio=1.0036666666666667, goal=6000.0, goalcategory='Low Goal', launched=datetime.datetime(2011, 6, 9, 14, 43, 2), launchmonth=6, main_category='Photography', name='Scar Tissue', pledged=6022.0, state='successful', usd_goal_real=6000.0, usd_pledged_real=6022.0)
Row(id=1022576045, backers=36863, campaignduration=39, category='Product Design', country='US', currency='USD', deadline=Date(17125), fundingratio=102.21207, goal=10000.0, goalcategory='Medium Goal', launched=datetime.datetime(2016, 10, 11, 17, 57, 34), launchmonth=10, main_category='Design', name='Polygons | The Flat 4-in-1 Measuring Spoon', pledged=1022120.7, state='successful', usd_goal_real=10000.0, usd_pledged_real=1022120.7)
Row(id=1002139381, backers=51, campaignduration=39, category="Children's Books", country='US', currency='USD', deadline=Date(16322), fundingratio=1.261, goal=2000.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 7, 31, 0, 54), launchmonth=7, main_category='Publishing', name='Tales from Sheepland: from the imagination of a child', pledged=2522.0, state='successful', usd_goal_real=2000.0, usd_pledged_real=2522.0)
Row(id=1011830662, backers=23, campaignduration=21, category='Shorts', country='US', currency='USD', deadline=Date(15693), fundingratio=1.0166666666666666, goal=1500.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 11, 27, 5, 32, 37), launchmonth=11, main_category='Film & Video', name='Red Sky Morning', pledged=1525.0, state='successful', usd_goal_real=1500.0, usd_pledged_real=1525.0)
Row(id=1012448004, backers=158, campaignduration=29, category='Dance', country='US', currency='USD', deadline=Date(15599), fundingratio=1.0099533333333333, goal=9000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 8, 17, 15, 18, 52), launchmonth=8, main_category='Dance', name='To Begin The World Over Again', pledged=9089.58, state='successful', usd_goal_real=9000.0, usd_pledged_real=9089.58)
Row(id=1008457418, backers=2, campaignduration=29, category='People', country='US', currency='USD', deadline=Date(16219), fundingratio=0.032, goal=2500.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 4, 29, 2, 9, 27), launchmonth=4, main_category='Photography', name='An Aesthetic Ethnography: The Land of Smiles', pledged=80.0, state='failed', usd_goal_real=2500.0, usd_pledged_real=80.0)
Row(id=1010661105, backers=32, campaignduration=44, category='Technology', country='DE', currency='EUR', deadline=Date(17067), fundingratio=0.24914994876953242, goal=40000.0, goalcategory='Medium Goal', launched=datetime.datetime(2016, 8, 9, 12, 27, 11), launchmonth=8, main_category='Technology', name='4-stage installation free Reverse Osmosis water purifier', pledged=9966.0, state='canceled', usd_goal_real=44856.12, usd_pledged_real=11175.9)
Row(id=1004500333, backers=172, campaignduration=29, category='Technology', country='US', currency='USD', deadline=Date(15547), fundingratio=1.012, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 6, 26, 1, 16, 25), launchmonth=6, main_category='Technology', name='Zombie USB Keychain (Zed 1.0)', pledged=5060.0, state='successful', usd_goal_real=5000.0, usd_pledged_real=5060.0)
Row(id=1003832819, backers=3, campaignduration=29, category='Gadgets', country='US', currency='USD', deadline=Date(16565), fundingratio=0.002692307692307692, goal=65000.0, goalcategory='Medium Goal', launched=datetime.datetime(2015, 4, 10, 20, 19, 15), launchmonth=4, main_category='Technology', name='Desktop CNC Compact Mill & Drill (Canceled)', pledged=175.0, state='canceled', usd_goal_real=65000.0, usd_pledged_real=175.0)
Row(id=1009041597, backers=40, campaignduration=59, category='3D Printing', country='US', currency='USD', deadline=Date(16396), fundingratio=0.651, goal=20000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 9, 23, 19, 54), launchmonth=9, main_category='Technology', name='3D Bean™ | Lifelike Fine 3D Photo Figurines of Yourself', pledged=13020.0, state='failed', usd_goal_real=20000.0, usd_pledged_real=13020.0)
Row(id=1004619032, backers=106, campaignduration=16, category='Shorts', country='US', currency='USD', deadline=Date(14960), fundingratio=1.161, goal=10000.0, goalcategory='Medium Goal', launched=datetime.datetime(2010, 11, 30, 7, 10, 40), launchmonth=11, main_category='Film & Video', name='"Violet Tendencies" (starring Mindy Cohn) on DVD', pledged=11610.0, state='successful', usd_goal_real=10000.0, usd_pledged_real=11610.0)
Row(id=1003294350, backers=3, campaignduration=29, category='Theater', country='US', currency='USD', deadline=Date(15268), fundingratio=0.02930232558139535, goal=21500.0, goalcategory='Medium Goal', launched=datetime.datetime(2011, 9, 21, 4, 4, 5), launchmonth=9, main_category='Theater', name='We Did It For You! - a historical musical (Canceled)', pledged=630.0, state='canceled', usd_goal_real=21500.0, usd_pledged_real=630.0)
Row(id=1024963922, backers=49, campaignduration=29, category='Thrillers', country='US', currency='USD', deadline=Date(16571), fundingratio=1.1012, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 4, 16, 20, 40, 14), launchmonth=4, main_category='Film & Video', name='White-Key, A Short Film by Nicholas Becher', pledged=5506.0, state='successful', usd_goal_real=5000.0, usd_pledged_real=5506.0)
Row(id=1013243732, backers=88, campaignduration=44, category='Comics', country='US', currency='USD', deadline=Date(16898), fundingratio=1.2060869565217391, goal=2300.0, goalcategory='Low Goal', launched=datetime.datetime(2016, 2, 22, 3, 6, 46), launchmonth=2, main_category='Comics', name='GROND  " Kallok of the Urughukai" Book One', pledged=2774.0, state='successful', usd_goal_real=2300.0, usd_pledged_real=2774.0)
Row(id=100609913, backers=193, campaignduration=34, category='Vegan', country='FR', currency='EUR', deadline=Date(16846), fundingratio=1.2229330590389766, goal=7500.0, goalcategory='Low Goal', launched=datetime.datetime(2016, 1, 11, 18, 30, 49), launchmonth=1, main_category='Food', name='Martin Persil, la cantine vegan à roulettes !', pledged=9172.0, state='successful', usd_goal_real=8321.96, usd_pledged_real=10177.2)
Row(id=1020833443, backers=0, campaignduration=59, category='Art', country='ES', currency='EUR', deadline=Date(16923), fundingratio=0.0, goal=100000.0, goalcategory='High Goal', launched=datetime.datetime(2016, 3, 3, 20, 20, 39), launchmonth=3, main_category='Art', name='VR Wonders - A first look at VR Tourism (Canceled)', pledged=0.0, state='canceled', usd_goal_real=114270.04, usd_pledged_real=0.0)
Row(id=1024713268, backers=33, campaignduration=19, category='Plays', country='US', currency='USD', deadline=Date(16446), fundingratio=1.00125, goal=4000.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 12, 22, 21, 53, 30), launchmonth=12, main_category='Theater', name='The History Boys at USC', pledged=4005.0, state='successful', usd_goal_real=4000.0, usd_pledged_real=4005.0)
Row(id=1008923900, backers=1, campaignduration=58, category='Product Design', country='IT', currency='EUR', deadline=Date(16807), fundingratio=0.0002867417456521797, goal=3500.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 11, 9, 17, 8, 17), launchmonth=11, main_category='Design', name='Stalish Artisan Design Lamps for Design Event in Milan', pledged=1.0, state='failed', usd_goal_real=3801.33, usd_pledged_real=1.09)
Row(id=1015354341, backers=9, campaignduration=29, category='Comics', country='US', currency='USD', deadline=Date(15460), fundingratio=0.136, goal=1000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 3, 31, 0, 24, 24), launchmonth=3, main_category='Comics', name='Unimportant Conversations', pledged=136.0, state='failed', usd_goal_real=1000.0, usd_pledged_real=136.0)
Row(id=1011810104, backers=6, campaignduration=30, category='Indie Rock', country='US', currency='USD', deadline=Date(15507), fundingratio=0.25, goal=500.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 5, 16, 4, 43, 44), launchmonth=5, main_category='Music', name='Nick Ladish 2012 EP Project', pledged=125.0, state='failed', usd_goal_real=500.0, usd_pledged_real=125.0)
Row(id=1020851909, backers=203, campaignduration=31, category='Video Games', country='US', currency='USD', deadline=Date(16391), fundingratio=0.014120588235294117, goal=850000.0, goalcategory='High Goal', launched=datetime.datetime(2014, 10, 16, 20, 1, 5), launchmonth=10, main_category='Games', name='Everstar (Canceled)', pledged=12002.5, state='canceled', usd_goal_real=850000.0, usd_pledged_real=12002.5)
Row(id=1006239815, backers=19, campaignduration=29, category='Shorts', country='US', currency='USD', deadline=Date(15709), fundingratio=0.2625, goal=1200.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 12, 5, 7, 44, 47), launchmonth=12, main_category='Film & Video', name='The Cage (SENIOR THESIS PROJECT) (Canceled)', pledged=315.0, state='canceled', usd_goal_real=1200.0, usd_pledged_real=315.0)
Row(id=100669275, backers=0, campaignduration=29, category='Digital Art', country='US', currency='USD', deadline=Date(14965), fundingratio=0.0, goal=100000.0, goalcategory='High Goal', launched=datetime.datetime(2010, 11, 22, 1, 28), launchmonth=11, main_category='Art', name='Chicano Art-Adan Hernandez-A Journey Into Chicano Noir', pledged=0.0, state='failed', usd_goal_real=100000.0, usd_pledged_real=0.0)
Row(id=1009083517, backers=21, campaignduration=44, category='Design', country='US', currency='USD', deadline=Date(17383), fundingratio=0.025046153846153846, goal=65000.0, goalcategory='Medium Goal', launched=datetime.datetime(2017, 6, 21, 0, 47, 4), launchmonth=6, main_category='Design', name='PediPocket: The Pinnacle of the Throw Blanket Experience!', pledged=1628.0, state='failed', usd_goal_real=65000.0, usd_pledged_real=1628.0)
Row(id=1006405499, backers=0, campaignduration=29, category='Woodworking', country='GB', currency='GBP', deadline=Date(16680), fundingratio=0.0, goal=200.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 8, 3, 17, 55, 44), launchmonth=8, main_category='Crafts', name='UK Salmon Laders', pledged=0.0, state='failed', usd_goal_real=304.53, usd_pledged_real=0.0)
Row(id=1023751719, backers=2, campaignduration=29, category='Product Design', country='AU', currency='AUD', deadline=Date(16443), fundingratio=3.079445926440916e-05, goal=65000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 12, 9, 1, 33, 14), launchmonth=12, main_category='Design', name='The suspended ceiling table', pledged=2.0, state='failed', usd_goal_real=52931.6, usd_pledged_real=1.63)
Row(id=1025029146, backers=0, campaignduration=29, category='Food', country='US', currency='USD', deadline=Date(16317), fundingratio=0.0, goal=40000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 8, 5, 18, 19, 51), launchmonth=8, main_category='Food', name='Hog City Cereal Bar', pledged=0.0, state='failed', usd_goal_real=40000.0, usd_pledged_real=0.0)
Row(id=1022172175, backers=0, campaignduration=29, category='Pop', country='US', currency='USD', deadline=Date(16365), fundingratio=0.0, goal=500.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 9, 22, 3, 52, 31), launchmonth=9, main_category='Music', name='Music Video Campaign', pledged=0.0, state='failed', usd_goal_real=500.0, usd_pledged_real=0.0)
Row(id=1016273264, backers=17, campaignduration=59, category='Rock', country='US', currency='USD', deadline=Date(15223), fundingratio=0.28514285714285714, goal=3500.0, goalcategory='Low Goal', launched=datetime.datetime(2011, 7, 8, 6, 12, 2), launchmonth=7, main_category='Music', name="Moozgit's debut album!!!", pledged=998.0, state='failed', usd_goal_real=3500.0, usd_pledged_real=998.0)
Row(id=1002131859, backers=152, campaignduration=32, category='Country & Folk', country='US', currency='USD', deadline=Date(17056), fundingratio=253.75, goal=20.0, goalcategory='Low Goal', launched=datetime.datetime(2016, 8, 10, 16, 47, 26), launchmonth=8, main_category='Music', name='Midwest Side Stories', pledged=5075.0, state='successful', usd_goal_real=20.0, usd_pledged_real=5075.0)
Row(id=1020998676, backers=8, campaignduration=29, category='Product Design', country='US', currency='USD', deadline=Date(15522), fundingratio=0.164, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 6, 1, 1, 9, 49), launchmonth=6, main_category='Design', name='Sundialer ~ The Round Sunbathing and Multi Purpose Mat', pledged=820.0, state='failed', usd_goal_real=5000.0, usd_pledged_real=820.0)
Row(id=1003938077, backers=59, campaignduration=29, category='Music', country='US', currency='USD', deadline=Date(15459), fundingratio=2.1575863636363635, goal=2200.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 3, 30, 9, 3, 59), launchmonth=3, main_category='Music', name='Two Boys and a Bow Tie Tour', pledged=4746.69, state='successful', usd_goal_real=2200.0, usd_pledged_real=4746.69)
Row(id=1005359971, backers=32, campaignduration=29, category='Indie Rock', country='US', currency='USD', deadline=Date(16572), fundingratio=1.02, goal=2000.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 4, 17, 20, 42, 45), launchmonth=4, main_category='Music', name='Telemetry Webisodes', pledged=2040.0, state='successful', usd_goal_real=2000.0, usd_pledged_real=2040.0)
Row(id=101845091, backers=7, campaignduration=29, category='Fashion', country='US', currency='USD', deadline=Date(15528), fundingratio=0.2012, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 6, 7, 18, 42, 23), launchmonth=6, main_category='Fashion', name='The Faetell Dress Shirt', pledged=1006.0, state='failed', usd_goal_real=5000.0, usd_pledged_real=1006.0)
Row(id=1016595269, backers=7, campaignduration=41, category='Shorts', country='GB', currency='GBP', deadline=Date(15706), fundingratio=0.10500227858690156, goal=1000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 11, 20, 22, 5, 3), launchmonth=11, main_category='Film & Video', name='Bruised (A Prequel To Shanked) - A film on Domestic Violence', pledged=105.0, state='failed', usd_goal_real=1601.87, usd_pledged_real=168.2)
Row(id=1022016221, backers=37, campaignduration=58, category='Documentary', country='US', currency='USD', deadline=Date(16314), fundingratio=0.17951099999999998, goal=10000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 7, 4, 1, 51, 59), launchmonth=7, main_category='Film & Video', name='Walking To My Friends', pledged=1795.11, state='failed', usd_goal_real=10000.0, usd_pledged_real=1795.11)
Row(id=1024117688, backers=2, campaignduration=4, category='Crafts', country='US', currency='USD', deadline=Date(16629), fundingratio=0.044, goal=500.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 7, 8, 5, 26, 30), launchmonth=7, main_category='Crafts', name='River rock accent mats', pledged=22.0, state='failed', usd_goal_real=500.0, usd_pledged_real=22.0)
Row(id=1006312961, backers=10, campaignduration=29, category="Children's Books", country='US', currency='USD', deadline=Date(16721), fundingratio=0.15745454545454546, goal=2750.0, goalcategory='Low Goal', launched=datetime.datetime(2015, 9, 13, 4, 22, 19), launchmonth=9, main_category='Publishing', name='The Shepherd', pledged=433.0, state='failed', usd_goal_real=2750.0, usd_pledged_real=433.0)
Row(id=1019835891, backers=21, campaignduration=29, category='Film & Video', country='US', currency='USD', deadline=Date(15541), fundingratio=0.02422, goal=50000.0, goalcategory='Medium Goal', launched=datetime.datetime(2012, 6, 20, 18, 53, 3), launchmonth=6, main_category='Film & Video', name='THE ORPHAN KILLER "BEHIND THE MURDER" (KILLSTARTER)', pledged=1211.0, state='canceled', usd_goal_real=50000.0, usd_pledged_real=1211.0)
Row(id=101941587, backers=25, campaignduration=29, category='Video Games', country='US', currency='USD', deadline=Date(16194), fundingratio=0.010183333333333334, goal=60000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 4, 4, 23, 26, 56), launchmonth=4, main_category='Games', name='Dahlia (Canceled)', pledged=611.0, state='canceled', usd_goal_real=60000.0, usd_pledged_real=611.0)
Row(id=1015621562, backers=0, campaignduration=32, category='Nonfiction', country='US', currency='USD', deadline=Date(16428), fundingratio=0.0, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 11, 21, 18, 29, 5), launchmonth=11, main_category='Publishing', name='Fatherhood..987 Years of Experience (Canceled)', pledged=0.0, state='canceled', usd_goal_real=5000.0, usd_pledged_real=0.0)
Row(id=1011073287, backers=101, campaignduration=29, category='Documentary', country='US', currency='USD', deadline=Date(15707), fundingratio=0.35891428571428574, goal=35000.0, goalcategory='Medium Goal', launched=datetime.datetime(2012, 12, 3, 22, 33, 46), launchmonth=12, main_category='Film & Video', name='ACTION! Master Class with Nicholas Ray', pledged=12562.0, state='failed', usd_goal_real=35000.0, usd_pledged_real=12562.0)
Row(id=1016537809, backers=0, campaignduration=58, category='Nonfiction', country='US', currency='USD', deadline=Date(15414), fundingratio=0.0, goal=4000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 1, 16, 0, 52, 29), launchmonth=1, main_category='Publishing', name='The design and implementation of a class-less economic state', pledged=0.0, state='failed', usd_goal_real=4000.0, usd_pledged_real=0.0)
Row(id=1020616269, backers=214, campaignduration=27, category='Playing Cards', country='GB', currency='GBP', deadline=Date(16418), fundingratio=1.0252537014030074, goal=5900.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 11, 16, 1, 17, 14), launchmonth=11, main_category='Games', name='Fishing For Compliments Playing Cards', pledged=6049.0, state='successful', usd_goal_real=9232.31, usd_pledged_real=9465.46)
Row(id=1011664710, backers=21, campaignduration=42, category='Rock', country='US', currency='USD', deadline=Date(14764), fundingratio=1.1242857142857143, goal=700.0, goalcategory='Low Goal', launched=datetime.datetime(2010, 4, 22, 20, 27, 52), launchmonth=4, main_category='Music', name="28 degrees taurus' new album and US tour 2010!", pledged=787.0, state='successful', usd_goal_real=700.0, usd_pledged_real=787.0)
Row(id=101234917, backers=120, campaignduration=29, category='Product Design', country='US', currency='USD', deadline=Date(16729), fundingratio=2.6349, goal=10000.0, goalcategory='Medium Goal', launched=datetime.datetime(2015, 9, 21, 18, 28, 54), launchmonth=9, main_category='Design', name='Modern Cornhole', pledged=26349.0, state='successful', usd_goal_real=10000.0, usd_pledged_real=26349.0)
Row(id=1005422939, backers=24, campaignduration=16, category='Design', country='CA', currency='CAD', deadline=Date(16392), fundingratio=0.8460083323950006, goal=500.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 11, 1, 21, 21, 41), launchmonth=11, main_category='Design', name='A Ninjutsu Pencil Holder', pledged=423.0, state='failed', usd_goal_real=444.05, usd_pledged_real=375.67)
Row(id=1011339921, backers=412, campaignduration=28, category='Periodicals', country='US', currency='USD', deadline=Date(16063), fundingratio=0.5008181203515889, goal=147900.0, goalcategory='High Goal', launched=datetime.datetime(2013, 11, 25, 19, 59, 59), launchmonth=11, main_category='Publishing', name='Video Watchdog Digital Archive for iPad, Android & Windows', pledged=74071.0, state='canceled', usd_goal_real=147900.0, usd_pledged_real=74071.0)

In [22]:
rows = session.execute("SELECT * FROM ks1.kickstarter")
df_cassandra = pd.DataFrame(rows)

In [23]:
rows = session.execute("SELECT * FROM ks1.kickstarter LIMIT 10")
for row in rows:
    print(row)

Row(id=1001524172, backers=20, campaignduration=44, category='Photography', country='US', currency='USD', deadline=Date(15179), fundingratio=1.0036666666666667, goal=6000.0, goalcategory='Low Goal', launched=datetime.datetime(2011, 6, 9, 14, 43, 2), launchmonth=6, main_category='Photography', name='Scar Tissue', pledged=6022.0, state='successful', usd_goal_real=6000.0, usd_pledged_real=6022.0)
Row(id=1022576045, backers=36863, campaignduration=39, category='Product Design', country='US', currency='USD', deadline=Date(17125), fundingratio=102.21207, goal=10000.0, goalcategory='Medium Goal', launched=datetime.datetime(2016, 10, 11, 17, 57, 34), launchmonth=10, main_category='Design', name='Polygons | The Flat 4-in-1 Measuring Spoon', pledged=1022120.7, state='successful', usd_goal_real=10000.0, usd_pledged_real=1022120.7)
Row(id=1002139381, backers=51, campaignduration=39, category="Children's Books", country='US', currency='USD', deadline=Date(16322), fundingratio=1.261, goal=2000.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 7, 31, 0, 54), launchmonth=7, main_category='Publishing', name='Tales from Sheepland: from the imagination of a child', pledged=2522.0, state='successful', usd_goal_real=2000.0, usd_pledged_real=2522.0)
Row(id=1011830662, backers=23, campaignduration=21, category='Shorts', country='US', currency='USD', deadline=Date(15693), fundingratio=1.0166666666666666, goal=1500.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 11, 27, 5, 32, 37), launchmonth=11, main_category='Film & Video', name='Red Sky Morning', pledged=1525.0, state='successful', usd_goal_real=1500.0, usd_pledged_real=1525.0)
Row(id=1012448004, backers=158, campaignduration=29, category='Dance', country='US', currency='USD', deadline=Date(15599), fundingratio=1.0099533333333333, goal=9000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 8, 17, 15, 18, 52), launchmonth=8, main_category='Dance', name='To Begin The World Over Again', pledged=9089.58, state='successful', usd_goal_real=9000.0, usd_pledged_real=9089.58)
Row(id=1008457418, backers=2, campaignduration=29, category='People', country='US', currency='USD', deadline=Date(16219), fundingratio=0.032, goal=2500.0, goalcategory='Low Goal', launched=datetime.datetime(2014, 4, 29, 2, 9, 27), launchmonth=4, main_category='Photography', name='An Aesthetic Ethnography: The Land of Smiles', pledged=80.0, state='failed', usd_goal_real=2500.0, usd_pledged_real=80.0)
Row(id=1010661105, backers=32, campaignduration=44, category='Technology', country='DE', currency='EUR', deadline=Date(17067), fundingratio=0.24914994876953242, goal=40000.0, goalcategory='Medium Goal', launched=datetime.datetime(2016, 8, 9, 12, 27, 11), launchmonth=8, main_category='Technology', name='4-stage installation free Reverse Osmosis water purifier', pledged=9966.0, state='canceled', usd_goal_real=44856.12, usd_pledged_real=11175.9)
Row(id=1004500333, backers=172, campaignduration=29, category='Technology', country='US', currency='USD', deadline=Date(15547), fundingratio=1.012, goal=5000.0, goalcategory='Low Goal', launched=datetime.datetime(2012, 6, 26, 1, 16, 25), launchmonth=6, main_category='Technology', name='Zombie USB Keychain (Zed 1.0)', pledged=5060.0, state='successful', usd_goal_real=5000.0, usd_pledged_real=5060.0)
Row(id=1003832819, backers=3, campaignduration=29, category='Gadgets', country='US', currency='USD', deadline=Date(16565), fundingratio=0.002692307692307692, goal=65000.0, goalcategory='Medium Goal', launched=datetime.datetime(2015, 4, 10, 20, 19, 15), launchmonth=4, main_category='Technology', name='Desktop CNC Compact Mill & Drill (Canceled)', pledged=175.0, state='canceled', usd_goal_real=65000.0, usd_pledged_real=175.0)
Row(id=1009041597, backers=40, campaignduration=59, category='3D Printing', country='US', currency='USD', deadline=Date(16396), fundingratio=0.651, goal=20000.0, goalcategory='Medium Goal', launched=datetime.datetime(2014, 9, 23, 19, 54), launchmonth=9, main_category='Technology', name='3D Bean™ | Lifelike Fine 3D Photo Figurines of Yourself', pledged=13020.0, state='failed', usd_goal_real=20000.0, usd_pledged_real=13020.0)

# Queries

## 1) What is the success rate for each main category?

In [ ]:
success_rate_by_category = df_cassandra.groupby('main_category')['state'] \
                                       .apply(lambda x: (x == 'successful').sum() / len(x) * 100)

print("Success rate for each main category:")
print(success_rate_by_category.sort_values(ascending=False))

Success rate for each main category:
main_category
Dance           70.370370
Theater         57.534247
Comics          54.729730
Music           46.153846
Art             41.860465
Games           37.860082
Film & Video    37.125749
Design          34.961440
Food            29.354839
Photography     29.032258
Publishing      28.149606
Fashion         26.449275
Crafts          22.881356
Journalism      22.413793
Technology      21.445783
Name: state, dtype: float64

## 2) Which countries have the highest average pledged amount in USD?

In [ ]:
average_pledged_by_country = df_cassandra.groupby('country')['usd_pledged_real'] \
                                        .mean() \
                                        .sort_values(ascending=False)

print("Countries with the highest average pledged amount in USD:")
print(average_pledged_by_country.head(10))

Countries with the highest average pledged amount in USD:
country
NL    126536.320244
HK     29643.352727
DE     22685.989818
CH     11707.785000
NZ     10631.409286
US     10361.291948
IE      9595.215333
LU      8612.550000
ES      8512.114839
CA      7047.207110
Name: usd_pledged_real, dtype: float64

## 3) Which 5 projects have the highest funding ratio?

In [ ]:
highest_funding_ratio_projects = df_cassandra.sort_values(by='fundingratio', ascending=False).head(5)

print("Top 5 projects with the highest funding ratio:")
display(highest_funding_ratio_projects[['name', 'fundingratio']])

Top 5 projects with the highest funding ratio:

                                                   name  fundingratio
1238  The $1 Play What You Want Mystery Campaign RPG...   4773.910000
2113  Kenophania: How A Song Is Created (Interactive...    700.323308
1864        Wholesters- A new way to Whold your things!    566.000000
29                                 Midwest Side Stories    253.750000
4081  Redefining Italian Luxury Watches - Filippo Lo...    240.477358

## 4) Among failed projects, which category has the highest number of failures?

In [ ]:
failed_projects = df_cassandra[df_cassandra['state'] == 'failed']

# Count number of failed projects per main category
failed_categories_count = failed_projects['main_category'].value_counts()

print("Category with the highest number of failures:")
print(failed_categories_count.head(1))

Category with the highest number of failures:
main_category
Film & Video    453
Name: count, dtype: int64

## 5)What is the average campaign duration for successful vs failed projects?

In [ ]:
average_duration_by_state = df_cassandra.groupby('state')['campaignduration'].mean()

print("Average campaign duration for successful vs. failed projects:")
print(average_duration_by_state[['successful', 'failed']])

Average campaign duration for successful vs. failed projects:
state
successful    30.882614
failed        34.286474
Name: campaignduration, dtype: float64

## 6)Which month has the highest number of successful projects?

In [ ]:
successful_projects = df_cassandra[df_cassandra['state'] == 'successful']

# Count successful projects by launch month
successful_projects_by_month = successful_projects['launchmonth'].value_counts().sort_index()

# Find the month with the highest number of successful projects
highest_month = successful_projects_by_month.idxmax()
max_projects = successful_projects_by_month.max()

print(f"The month with the highest number of successful projects is month {highest_month} with {max_projects} projects.")
print("Successful projects by month:")
print(successful_projects_by_month)

The month with the highest number of successful projects is month 5 with 176 projects.
Successful projects by month:
launchmonth
1     109
2     153
3     152
4     154
5     176
6     159
7     161
8     162
9     165
10    165
11    164
12     86
Name: count, dtype: int64

## 7)What is the average number of backers per main category?

In [ ]:
average_backers_by_category = df_cassandra.groupby('main_category')['backers'].mean().sort_values(ascending=False)
print("Average number of backers per main category:")
print(average_backers_by_category)

Average number of backers per main category:
main_category
Design          363.694087
Technology      251.407229
Games           238.707819
Comics          114.662162
Fashion          65.753623
Food             64.238710
Dance            54.351852
Film & Video     53.805988
Photography      45.941935
Music            44.388811
Publishing       42.200787
Journalism       41.862069
Art              39.423773
Theater          37.308219
Crafts           21.050847
Name: backers, dtype: float64

## 8)What percentage of projects reached or exceeded their goal?

In [ ]:
projects_reached_goal = df_cassandra[df_cassandra['usd_pledged_real'] >= df_cassandra['usd_goal_real']]

# Calculate the percentage
percentage_reached_goal = (len(projects_reached_goal) / len(df_cassandra)) * 100

print(f"Percentage of projects that reached or exceeded their goal: {percentage_reached_goal:.2f}%")

Percentage of projects that reached or exceeded their goal: 36.90%