In [25]:
!pip install pymongo

Requirement already satisfied: pymongo in /usr/local/lib/python3.12/dist-packages (4.16.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo) (2.8.0)

In [26]:
import pymongo
from pymongo import MongoClient
import urllib.parse
from bson.json_util import dumps

In [27]:
# replace <USERNAME> with your own MongoDB username (without the angle brackets)
# replace <PASSWORD> with your own MongoDB password (without the angle brackets)
# replace <CLUSTERNAME> with your cluster's name (without the angle brackets)
url = "mongodb+srv://maryam:maryam05@cluster0.4pjielh.mongodb.net/?appName=Cluster0"
cluster = MongoClient(url)

In [28]:
db = cluster["Assignment1"] # replace <CLUSTERNAME> with your cluster's name
collection = db["MongoKS"]

In [29]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/kick_starter.csv')

# Print the first 10 rows of the DataFrame in a table format
print("First 10 rows of the DataFrame:")
display(df.head(10))

# Print the shape of the DataFrame
print("\nShape of the DataFrame:")
print(df.shape)

First 10 rows of the DataFrame:

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00

Shape of the DataFrame:
(378661, 15)

## Dropped usd_pledged coloumn

In [30]:
df = df.drop(columns=['usd pledged'])

print("DataFrame after dropping 'usd_pledged' column:")
display(df.head())

DataFrame after dropping 'usd_pledged' column:

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## unifing column names

In [31]:
df = df.rename(columns={'ID': 'id'})

print("DataFrame after renaming 'ID' to 'id':")
display(df.head())

DataFrame after renaming 'ID' to 'id':

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## Checking for duplicates

In [32]:
print(f"DataFrame shape before dropping duplicates: {df.shape}")

duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_rows}")

df = df.drop_duplicates()

print(f"DataFrame shape after dropping duplicates: {df.shape}")
display(df.head())

DataFrame shape before dropping duplicates: (378661, 14)
Number of duplicate rows found: 0
DataFrame shape after dropping duplicates: (378661, 14)

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00

## Handling missing values

In [33]:
print("Missing values per column:")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

print("\nPercentage of missing values per column:")
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

Missing values per column:
name    4
dtype: int64

Percentage of missing values per column:
name    0.001056
dtype: float64

In [34]:
print("DataFrame Info (including data types):")
df.info()

DataFrame Info (including data types):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                378661 non-null  int64
 1   name              378657 non-null  object
 2   category          378661 non-null  object
 3   main_category     378661 non-null  object
 4   currency          378661 non-null  object
 5   deadline          378661 non-null  object
 6   goal              378661 non-null  float64
 7   launched          378661 non-null  object
 8   pledged           378661 non-null  float64
 9   state             378661 non-null  object
 10  backers           378661 non-null  int64
 11  country           378661 non-null  object
 12  usd_pledged_real  378661 non-null  float64
 13  usd_goal_real     378661 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 40.4+ MB

In [35]:
print(f"DataFrame shape before dropping missing values in 'name': {df.shape}")

df = df.dropna(subset=['name'])

print(f"DataFrame shape after dropping missing values in 'name': {df.shape}")

DataFrame shape before dropping missing values in 'name': (378661, 14)
DataFrame shape after dropping missing values in 'name': (378657, 14)

## Drop projects where state = live

In [36]:
print(f"DataFrame shape before dropping 'live' projects: {df.shape}")

df = df[df['state'] != 'live']

print(f"DataFrame shape after dropping 'live' projects: {df.shape}")

DataFrame shape before dropping 'live' projects: (378657, 14)
DataFrame shape after dropping 'live' projects: (375858, 14)

## CampaignDuration (in days)

In [37]:
df['launched'] = pd.to_datetime(df['launched'])
df['deadline'] = pd.to_datetime(df['deadline'])

df['CampaignDuration'] = (df['deadline'] - df['launched']).dt.days

print("DataFrame with 'CampaignDuration' column:")
display(df.head())
print("\nData type of 'CampaignDuration' column:")
print(df['CampaignDuration'].dtype)

DataFrame with 'CampaignDuration' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55

Data type of 'CampaignDuration' column:
int64

## FundingRatio
FundingRatio =
usd_pledged_real/
usd_goal_real

In [38]:
df['FundingRatio'] = df['usd_pledged_real'] / df['usd_goal_real']

print("DataFrame with 'FundingRatio' column:")
display(df.head())

DataFrame with 'FundingRatio' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795

## GoalCategory
– Low Goal (< $10,000)
– Medium Goal ($10,000 – $100,000)
– High Goal (> $100,000)

In [39]:
bins = [-float('inf'), 10000, 100000, float('inf')]
labels = ['Low Goal', 'Medium Goal', 'High Goal']

df['GoalCategory'] = pd.cut(df['usd_goal_real'], bins=bins, labels=labels, right=False)

print("DataFrame with 'GoalCategory' column:")
display(df.head())
print("\nValue counts for 'GoalCategory':")
print(df['GoalCategory'].value_counts())

DataFrame with 'GoalCategory' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000,Low Goal
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700,Medium Goal
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889,Medium Goal
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200,Low Goal
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795,Medium Goal

Value counts for 'GoalCategory':
GoalCategory
Low Goal       231823
Medium Goal    128011
High Goal       16024
Name: count, dtype: int64

##  LaunchMonth

In [40]:
df['LaunchMonth'] = df['launched'].dt.month

print("DataFrame with 'LaunchMonth' column:")
display(df.head())

DataFrame with 'LaunchMonth' column:

,id,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory,LaunchMonth
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000,Low Goal,8
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700,Medium Goal,9
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889,Medium Goal,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200,Low Goal,3
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795,Medium Goal,7

In [41]:
# Clear the collection to avoid duplicate inserts
collection.delete_many({})

# Convert dataframe to dictionary documents
data = df.to_dict("records")

# Insert cleaned data into MongoDB
collection.insert_many(data)

print("Cleaned dataset inserted into MongoDB")

Cleaned dataset inserted into MongoDB

#**Queries**

## 1)What is the success rate for each main category?

In [42]:
pipeline = [
    {
        "$group": {
            "_id": "$main_category",
            "total_projects": {"$sum": 1},
            "successful_projects": {
                "$sum": {"$cond": [{"$eq": ["$state", "successful"]}, 1, 0]}
            }
        }
    },
    {
        "$project": {
            "success_rate": {
                "$multiply": [
                    {"$divide": ["$successful_projects", "$total_projects"]},
                    100
                ]
            }
        }
    },
    {"$sort": {"success_rate": -1}}
]

results = list(collection.aggregate(pipeline))

print("Success rate for each main category:")

for r in results:
    print(f"{r['_id']:<15} {r['success_rate']:.6f}")

Success rate for each main category:
Dance           62.346667
Theater         60.099338
Comics          54.379596
Music           46.859810
Art             41.168896
Film & Video    37.347436
Games           35.824056
Design          35.445505
Publishing      31.080227
Photography     30.798621
Food            24.920141
Fashion         24.785075
Crafts          24.218482
Journalism      21.422523
Technology      19.986332

## 2)Which countries have the highest average pledged amount in USD?

In [43]:
pipeline = [
    {
        "$group":{
            "_id":"$country",
            "avg_pledged":{"$avg":"$usd_pledged_real"}
        }
    },
    {"$sort":{"avg_pledged":-1}}
]

results=list(collection.aggregate(pipeline))

print("Average pledged amount per country:")
for r in results:
    print(f"{r['_id']:<10} {r['avg_pledged']:.2f}")

Average pledged amount per country:
CH         17166.34
HK         16571.64
AT         16356.80
FR         11755.75
SG         10459.98
NL         10271.86
US         9690.14
DE         9654.60
LU         7671.27
SE         7599.59
GB         7049.37
BE         6897.67
DK         6892.96
CA         6205.42
AU         5982.11
IT         5773.73
ES         5711.84
NZ         5424.76
IE         5197.64
NO         3599.01
N,0"       2950.63
JP         2918.01
MX         1439.59

## 3)Which 5 projects have the highest funding ratio?

In [44]:
pipeline = [
    {"$sort":{"FundingRatio":-1}},
    {"$limit":5},
    {
        "$project":{
            "name":1,
            "FundingRatio":1
        }
    }
]

results=list(collection.aggregate(pipeline))

print("Top 5 projects with highest funding ratio:")
for r in results:
    print(f"{r['name']:<60} {r['FundingRatio']:.4f}")

Top 5 projects with highest funding ratio:
VULFPECK /// The Beautiful Game                              104277.8900
Re-covering with Friends                                     68764.1000
VULFPECK /// Thrill of the Arts                              55266.5700
Energy Hook                                                  41535.0100
Band of Brothers 2nd Chance                                  32843.0000

## 4)Among failed projects, which category has the highest number of failures?

In [45]:
pipeline = [
    {"$match": {"state": "failed"}},  # Only failed projects
    {
        "$group": {
            "_id": "$main_category",
            "failures": {"$sum": 1}      # Count failures per category
        }
    },
    {"$sort": {"failures": -1}},        # Sort descending
    {"$limit": 1}                        # Only take the top category
]

results = list(collection.aggregate(pipeline))

print("Category with the highest number of failures:")
for r in results:
    print(f"{r['_id']:<15} {r['failures']}")

Category with the highest number of failures:
Film & Video    32903

## 5)What is the average campaign duration for successful vs failed projects?

In [46]:
pipeline = [
    {
        "$match": {"state": {"$in": ["successful", "failed"]}}  # Only include these two states
    },
    {
        "$project": {
            "state": 1,
            "duration": {
                "$divide": [
                    {"$subtract": [{"$toDate": "$deadline"}, {"$toDate": "$launched"}]},
                    1000*60*60*24  # Convert milliseconds to days
                ]
            }
        }
    },
    {
        "$group": {
            "_id": "$state",
            "avg_duration": {"$avg": "$duration"}
        }
    }
]

results = list(collection.aggregate(pipeline))

print("Average campaign duration for successful vs failed projects:")
for r in results:
    print(f"{r['_id']:<12} {r['avg_duration']:.2f} days")

Average campaign duration for successful vs failed projects:
failed       34.61 days
successful   31.59 days

## 6)Which month has the highest number of successful projects?

In [47]:
# Pipeline to get number of successful projects per month
pipeline = [
    {"$match": {"state": "successful"}},  # Only successful projects
    {
        "$project": {
            "LaunchMonth": {"$month": {"$toDate": "$launched"}}
        }
    },
    {
        "$group": {
            "_id": "$LaunchMonth",
            "count": {"$sum": 1}
        }
    },
    {"$sort": {"_id": 1}}  # Sort by month ascending
]

results = list(collection.aggregate(pipeline))

# Create a dictionary to simulate Pandas Series output
month_counts = {r["_id"]: r["count"] for r in results}

# Find the month with the highest number of successful projects
max_month = max(month_counts, key=month_counts.get)
max_count = month_counts[max_month]

print(f"The month with the highest number of successful projects is month {max_month} with {max_count} projects.\n")
print("Successful projects by month:")
print("LaunchMonth")
for month in range(1, 13):
    count = month_counts.get(month, 0)
    print(f"{month:<5} {count}")

The month with the highest number of successful projects is month 3 with 12851 projects.

Successful projects by month:
LaunchMonth
1     9480
2     11003
3     12851
4     12093
5     12062
6     11773
7     11681
8     10820
9     11231
10    12350
11    11770
12    6842

## 7)What is the average number of backers per main category?

In [48]:
pipeline=[
    {
        "$group":{
            "_id":"$main_category",
            "avg_backers":{"$avg":"$backers"}
        }
    },
    {"$sort":{"avg_backers":-1}}
]

results=list(collection.aggregate(pipeline))

print("Average number of backers per category:")
for r in results:
    print(f"{r['_id']:<15} {r['avg_backers']:.2f}")

Average number of backers per category:
Games           323.72
Design          241.50
Technology      164.98
Comics          135.35
Film & Video    66.27
Fashion         61.84
Publishing      56.06
Food            54.36
Music           52.31
Theater         47.13
Dance           42.95
Art             42.27
Photography     39.74
Journalism      38.36
Crafts          27.46

## 8)What percentage of projects reached or exceeded their goal?

In [49]:
pipeline=[
    {
        "$group":{
            "_id":None,
            "total":{"$sum":1},
            "reached":{
                "$sum":{
                    "$cond":[
                        {"$gte":["$usd_pledged_real","$usd_goal_real"]},
                        1,
                        0
                    ]
                }
            }
        }
    },
    {
        "$project":{
            "percentage":{
                "$multiply":[{"$divide":["$reached","$total"]},100]
            }
        }
    }
]

results=list(collection.aggregate(pipeline))

print("Percentage of projects that reached or exceeded their goal:")
for r in results:
    print(f"{r['percentage']:.2f}%")

Percentage of projects that reached or exceeded their goal:
36.34%